#!/usr/bin/env perl
#
# camxes - make https://github.com/lojban/ilmentufa more useful on the
# CLI. the argument complexity comes from a desire to support `camxes do
# mo` which needs to be turned into `node run_camxes "do mo"` while not
# mixing any options into that ultimate single argument

chdir "TODOFIXME/ilmentufa" or die "chdir failed: $!\n";

my @args;
while ( my $arg = shift @ARGV ) {
    if ( $arg eq "--" ) {
        push @args, "@ARGV";
        last;
    }
    if ( $arg =~ m/^-/ ) {
        push @args, $arg;
        if ( $arg eq "-p" or $arg eq "-m" ) {
            push @args, shift @ARGV;
        }
        next;
    }
    push @args, "$arg @ARGV";
    last;
}

# NOTE node maybe is instead called nodejs on Linux?
exec qw(node run_camxes), @args;
