#!/usr/bin/env perl
#
# lojify - vi(1) filter to confirm that camxes can parse the input

chdir "$ENV{HOME}/co/third-party/ilmentufa" || exit 1;

$_ = do { local $/; readline };
print;
s/#[^\n]+//g;
exec {'node'} qw{node run_camxes -m T}, $_
