.Dd April 21 2021
.Dt MITYSISKU 1
.nh
.Os
.Sh NAME
.Nm mitysisku
.Nd lojban dictionary search
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl DegHlnRx
.Op Fl s Ar selma'o
.Op Fl t Ar type
.Ar word
.Ek
.Sh DESCRIPTION
.Nm
performs lojban dictionary searches. By default lojban is searched
for; use
.Fl n
to instead search for
.Ar word
in the English-to-Lojban dictionary.
Options:
.Bl -tag -width -indent
.It Fl D
Search the text of the definition for the lojban word.
.Pp
Enables
.Fl l
as exact searches on definitions are not very productive.
.It Fl e
Exact
.Ar word
search. The default. This may be changed to a
.Fl l
search by other flags or inputs.
.It Fl g
Attempts a global lookup of all the cmavo and rafsi that may be
present in the
.Ar word .
This disables recursion and performs an exact word search. This flag is
ignored when searching the English dictionary. Will be called
automatically if simpler searches fail.
.It Fl H
Replaces \&' with \&h in lojban words printed by this program
(except not in the free-form NOTES or word definition fields). Input
always accepts both forms; input will be translated to \&' before
the search is made.
.Pp
This is a not official extension to the language.
.It Fl l
Use a
.Cm LIKE
.Ar word
search. This is done as
.Cm %word%
unless the
.Ar word
contains the
.Cm [_
characters, in which case that string will be used.
.It Fl n
Search the English dictionary instead of the Lojbanic one.
.It Fl R
Recurse; additionally looks up related words to the given
.Ar word .
Repeat this flag to increase the recursion depth. A global search
disables recursion. An
.Ar en
dictionary lookup likewise disables recursion.
.It Fl s Ar selmaho
Limit lojban results to only the given selma'o, such as 
.Ar KOhA3 .
The
.Ar word
may be ommited in which case a complete search of the selmaho given is
performed.
.It Fl t Ar type
Limit lojban results to only the given type, such as
.Ar gismu
or
.Ar lujvo .
The exact list of types can be obtained from the underlying database via
a query such as
.Pp
.Dl Ic SELECT DISTINCT(type) FROM jbo ORDER BY type;
.It Fl x
Excludes experimental words from the result.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Search the English dictionary,
.Dl $ Ic mitysisku -n cat
.Dl ...
.Pp
Or the Lojbanic dictionary
.Pp
.Dl $ Ic mitysisku \&"la'o\&"
.Dl ...
.Pp
or to avoid the need to shell quote the input
.Pp
.Dl $ Ic mitysisku laho
.Dl ...
.Pp
or to depart from official form in the output
.Pp
.Dl $ Ic mitysisku -H -e laho
.Dl ...
.Pp
The difference between a global and not-global search may be illustrated
by...look, squirrel!
.Pp
.Dl $ Ic mitysisku ricyratcu
.Dl ...
.Dl $ Ic mitysisku -g ricyratcu
.Dl ...
.Pp
Definition searches are sometimes necessary, for example if you recall a
cmavo with
.Qq under
in its definition but forgot it was
.Sy me'a
(undercut):
.Pp
.Dl $ Ic mitysisku -t cmavo -D under
.Dl ...
.Pp
All matches for a given selma'o can be made via:
.Pp
.Dl $ Ic mitysisku -s koha3 -l '%'
.Dl ...
.Pp
This is case insensitive as typing 
.Qq KOhA3
exactly would be annoying.
.Pp
.Nm
tries to parse cmavo compounds and lujvo but is by no means perfect at
this; it may be necessary to use
.Xr camxes 1
to parse phrases where the words have been mushed together randomly. In
particular bu-letterals probably are not parsed correctly.
.Xr jvocuhadju 1
can be used to confirm whether a particular form is valid:
.Pp
.Dl $ Ic camxes ive\&\\&'imlemlatu
.Dl (i [ve'i mlemlatu])
.Dl $ Ic jvocuhadju ve\&\\&'i melbi
.Dl Cannot use component [ve'i] in forming lujvo.
.Sh SEE ALSO
.Xr camxes 1 ,
.Xr jvocuhadju 1
.Pp
.Cm lefanva
converts the XML dictionary to a format
.Nm
can consume; this utility also contains the database schema:
.Pp
https://github.com/thrig/lingua
.Pp
Download the dictionary from
.Pp
https://jbovlaste.lojban.org/
.Pp
Meanwhile,
.Pp
https://github.com/lojban/jbofihe
.Pp
is the source for
.Xr jvocuhadju 1 .
.Sh AUTHOR
.An Jeremy Mates
.Sh BUGS
Only the English dictionary is supported though other languages should
in theory be simple to add support for. The parsing of lojban is not
very good. Etc.
