.Dd November  1 2018
.Dt MITYSISKU 1
.nh
.Os
.Sh NAME
.Nm mitysisku
.Nd lojban dictionary search
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl DegHlR
.Ar word
.Op Ar en|jbo
.Ek
.Sh DESCRIPTION
.Nm
performs lojban dictionary searches. By default lojban words are
searched for; append
.Ar en
to instead search for
.Ar word
in the English-to-Lojban dictionary.
Options:
.Bl -tag -width -indent
.It Fl D
Search the definition. That is, it searches the lojban side though looks
through the definition text which should be in some other language. This
was added because the language-to-lojban dictionary may be incomplete.
.Pp
Enables
.Fl l
as exact searches on definitions are not very productive.
.It Fl e
Exact
.Ar word
search. Not enabled by default, unless the
.Fl g
flag is used.
.It Fl g
Attempts a gismu lookup of all the gismu or rafsi that may be
present in the
.Ar word .
This disables recursion and performs an exact word search. This flag is
ignored when searching the English dictionary via
.Ar en .
.It Fl H
Replaces \&' with \&h in lojban words printed by this program
(except not in the free-form NOTES or word definition fields). Input
always accepts both forms; input will be translated to \&' before
the search is made.
.Pp
This is a not official extension to the language.
.It Fl l
Use a
.Cm LIKE
.Ar word
search. This is the default, and is done as
.Cm %word%
unless the
.Ar word
contains the
.Cm [_
characters, in which case that exact string will be used.
.It Fl R
Recurse; additionally looks up related words to the given
.Ar word .
Repeat this flag to increase the recursion depth. A gismu search
.Fl g
disables recursion. An
.Ar en
dictionary lookup likewise disables recursion.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Exact lookup on
.Ar la'o
as otherwise the default
.Cm LIKE
search finds too many false positives
.Pp
.Dl $ Ic mitysisku -e \&"la'o\&"
.Pp
or to avoid the need to shell quote the input
.Pp
.Dl $ Ic mitysisku -e laho
.Pp
or to depart from official form in the output
.Pp
.Dl $ Ic mitysisku -H -e laho
.Pp
Recursive search on anything containing
.Ar tricu
and also any related terms to those hits. Send to pager with support for
terminal escape codes.
.Pp
.Dl $ Ic mitysisku -R tricu \&| less -R
.Pp
The difference between a gismu and not-gismu search may be illustrated
by...look, squirrel!
.Pp
.Dl $ Ic mitysisku ricyratcu
.Dl ...
.Dl $ Ic mitysisku -g ricyratcu
.Sh SEE ALSO
.Cm lefanva
will be necessary to convert the XML dictionary to a format
.Nm
can consume; this utility also contains the database schema if one wants
to directly access that via SQL.
.Sh AUTHOR
.An Jeremy Mates
