#!/usr/bin/env perl
use 5.14.0;
use File::Spec ();
use Text::Unidecode qw(unidecode);

my $bridi = "@ARGV";

# allow ni'o or whatnot to be input as niho
$bridi =~ tr/h/'/;

my $filename = unidecode($bridi);
# ' back to h for filesystem
tr/'/h/, s/[^A-Za-z0-9_-]//g, $_ = lc, $_ .= '.wav' for $filename;

my $filepath = File::Spec->catfile( $ENV{HOME}, 'Desktop', $filename );

system( qw(speak -v test/jbo -w), $filepath, $bridi ) == 0
  or die "speak failed: $?\n";

system( 'afplay', $filepath );
